---                     
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-amf-n1n2
  namespace: free5gcore-superg
spec:        
  config: '{
             "cniVersion": "0.3.1",
             "type": "macvlan",
             "master": "eth0",
             "mode": "bridge",
             "ipam": {
                 "type": "static",
                 "addresses": [
                  {
                        "address": "172.16.10.20/24",
                        "gateway": "172.16.10.1"
                  }
               ]
           }
        }'

