apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-webui-config
  namespace: free5gcore-superg
data:
  webuicfg.conf: |
    info:
      version: 1.0.0
      description: WebUI initial local configuration
    
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://f5gc-mongodb:27017
